src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path 
from .views import home
from .views import AllRecipeView, RecipeDetailView
from .views import create_view, about_view

app_name= "recipes"

urlpatterns = [
    path("", home),
    path('list/', AllRecipeView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('create/', create_view, name='create'),
    path('about/', about_view, name='about'),

]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.IntegerField(help_text='in minutes')
    ingredients = models.CharField(max_length=300)
    directions = models.TextField(max_length=500)
    pic = models.ImageField(upload_to='recipes', default='no_image.jpg')

    def calculate_difficulty(self):
        difficulty = 'Undefined'
        ingredients = self.ingredients.split(', ')
        num_ingredients = len(ingredients)

        if self.cooking_time < 10: 
            if num_ingredients < 4:
                difficulty = 'Easy'
            else:
                difficulty = 'Medium'
        else: 
            if num_ingredients < 4:
                difficulty = 'Intermediate'
            else:
                difficulty = 'Hard'

        return difficulty
    
    def __str__(self):
        return str(self.name) 
    
    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

src/users/models.py
from django.db import models
from recipes.models import Recipe

# Create your models here.
class User(models.Model):
    name = models.CharField(help_text = 'Enter your name', max_length=120)
    stored_recipes = models.ForeignKey(Recipe, on_delete = models.CASCADE)

    def __str__(self):
        return f" {self.name}, stored recipes: {self.stored_recipes.name}"

src/recipes/forms.py
from django import forms

## Search recipes ##

class RecipeSearchForm(forms.Form):
    search_name = forms.CharField(required=False, label="Search by name")
    search_ingredient = forms.CharField(required=False, label="Search by ingredient")

## User create a recipe form ##

class CreateRecipeForm(forms.Form):
    name = forms.CharField(max_length=70, required=False)
    cooking_time = forms.IntegerField(help_text='in minutes', required=False)
    ingredients = forms.CharField(max_length=300, required=False)
    directions = forms.CharField(max_length=600, required=False)
    picture = forms.ImageField(required=False) 

src/recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/list')
        else:
            error_message = 'Oops . . . something went wrong'
    
    context = {
        'form': form,
        'error_message': error_message
    }
    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipeSearchForm, CreateRecipeForm
from .utils import get_popular_ingredients_chart

import pandas as pd 


# Create your views here.
def home(request):
    return render(request, "recipes/recipes_home.html")

class AllRecipeView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/all_recipes.html'

## search all recipes ##
    
    def get_queryset(self):
        queryset = super().get_queryset()
        
        search_name = self.request.GET.get("search_name")
        search_ingredient = self.request.GET.get("search_ingredient")

        if search_name:
            queryset = queryset.filter(name__icontains=search_name)
        if search_ingredient:
            queryset = queryset.filter(ingredients__icontains=search_ingredient)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()

        df = pd.DataFrame(list(queryset.values('id', 'name', 'cooking_time', 'pic')))
        recipes = df.to_dict("records") if not df.empty else []

        for recipe in recipes:
            recipe_instance = Recipe.objects.get(pk=recipe["id"])
            recipe["get_absolute_url"] = recipe_instance.get_absolute_url()
            recipe["pic_url"] = recipe_instance.pic.url if recipe_instance.pic else None

        context["object_list"] = recipes

        num_results = len(context["object_list"])
        title_parts = []

        search_name = self.request.GET.get("search_name")
        search_ingredient = self.request.GET.get("search_ingredient")

        if search_name:
            title_parts.append(f"'{search_name}' in the name")
        if search_ingredient:
            title_parts.append(f"'{search_ingredient}' in the ingredients")

        if title_parts:
            context['main_title'] = "Search results:"
            recipe_word = "Recipe" if num_results == 1 else "Recipes"
            details_intro = f"{recipe_word} with "
            context['search_details'] = details_intro + ", ".join(title_parts)
        else:
            context['main_title'] = "All recipes"
            context['search_results'] = "Search results"
        
        recipes_list = list(queryset.values('id', 'name','cooking_time', 'ingredients', 'directions', 'pic'))

        context["search_form"] = RecipeSearchForm(self.request.GET)
        context["show_all_recipes_button"] = bool(self.request.GET)
        context["popular_ingredients_chart"] = get_popular_ingredients_chart(recipes_list)

        return context

## Recipe details modal ##

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'search_params': self.request.GET.urlencode()
        })
        return context
    
def about_view(request):
    return render(request, 'recipes/about.html')

## form to create a recipe ## 

@login_required
def create_view(request):
    create_form = CreateRecipeForm (request.POST or None, request.FILES)
    name = None
    cooking_time = None
    ingredients = None
    directions = None
    pic = None

    if request.method == 'POST':

        try:
            recipe = Recipe.objects.create(
                name = request.POST.get('name'),
                cooking_time = request.POST.get('cooking_time'),
                ingredients = request.POST.get('ingredients'),
                directions = request.POST.get('direction'),
                pic = request.POST.get('pic')
            )

            recipe.save()

        except:
            print('Error!!!')

    context = {
        'create_form': create_form,
        'name': name,
        'cooking_time': cooking_time,
        'ingredients': ingredients,
        'directions': directions,
        'pic': pic,
    }

    return render(request, 'recipes/create_recipe.html', context)

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/recipes/templates/recipes/About.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
      rel="stylesheet"
    />
    <title>About Me</title>
  </head>
  <body>
    <div class="main-image">
      <img src="{% static 'recipes/images/recipe-home.jpg' %}" alt="home" />
    </div>
    <nav class="navbar">
      <div class="title">
        <h1>Recipe App</h1>
      </div>

      <div class="profile">
        <a href="/create/">Create Recipe</a>
        <a href="/about/">About Me</a>
        <a href="{%url 'logout' %}"> Logout </a>
      </div>
    </nav>

    <div class="recipe-modal">
      <span
        ><a class="main-header" href="{%url 'recipes:list' %}"
          >Back to all recipes</a
        ></span
      >
      <h2>Madison Housman, Web Developer</h2>

      <div>
        <div class="ing-dir">
          Hi! My name is Madison and I created this recipe app using Django,
          Python, HTML, CSS, and JavaScript. Check out the links below to see
          more of my work!
        </div>
        <div class="portfolio-link">
          <a href="https://madison24.github.io/portfolio-website/">Portfolio</a>
          <br />
          <a href="https://github.com/madison24">GitHub</a>
        </div>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/all_recipes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
      rel="stylesheet"
    />
    <title>Recipe App Main</title>
  </head>
  <body>
    <div class="main-image">
      <img src="{% static 'recipes/images/recipe-home.jpg' %}" alt="home" />
    </div>
    <nav class="navbar">
      <div class="title">
        <h1>Recipe App</h1>
      </div>

      <div class="profile">
        <a href="/create/">Create Recipe</a>

        <a href="/about/">About Me</a>

        <a href="{%url 'logout' %}"> Logout </a>
      </div>
    </nav>

    <div id="search-container" style="margin-left: 10px">
      <div class="search-holder">
        <div class="top-notch"></div>

        <form id="searchForm" method="get">
          {{ search_form.as_p }}
          <button type="submit" class="search-button">Search</button>
        </form>
      </div>
    </div>

    {% if search_details %}
    <h3 class="search-results">{{ search_details }}</h3>
    <a class="main-header" href="{%url 'recipes:list' %}"
      >Back to all recipes</a
    >
    {% endif %}

    <div class="all-recipes">
      {% for object in object_list %}
      <div class="recipe-item">
        <a class="recipe-name" href="{{object.get_absolute_url}}">
          {{object.name}}

          <div>
            {% if object.pic_url %}
            <img src="{{object.pic_url}}" class="recipe-pic" />
            {% endif %}
          </div>
          <div class="recipe-details">
            <b>Cooking Time: </b> {{object.cooking_time}} <br />
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br />
          </div>
        </a>
      </div>

      {% endfor %}
    </div>
    <!-- <div class="chart-container">
      <img
        src="data:image/png;base64, {{ popular_ingredients_chart }}"
        alt="popular ingredients chart"
      />
    </div> -->
  </body>
</html>

src/recipes/templates/recipes/create_recipe.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
      rel="stylesheet"
    />
    <title>Create A Recipe</title>
  </head>
  <body>
    <div class="main-image">
      <img src="{% static 'recipes/images/recipe-home.jpg' %}" alt="home" />
    </div>
    <nav class="navbar">
      <div class="title">
        <h1>Recipe App</h1>
      </div>

      <div class="profile">
        <a href="/create/">Create Recipe</a>
        <a href="/about/">About Me</a>
        <a href="{%url 'logout' %}"> Logout </a>
      </div>
    </nav>
    <div class="recipe-modal">
      <span
        ><a class="main-header" href="{%url 'recipes:list' %}"
          >Back to all recipes</a
        ></span
      >
      <div class="details-main">
        <h2>Create Recipe</h2>

        <div class="details-main">
          <div class="details-extra"></div>
          <div class="ing-dir">
            <form action="" method="POST">
              {% csrf_token %} {{create_form.as_p}}
              <button class="button" type="submit">Create</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/recipe_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
      rel="stylesheet"
    />
    <title>Recipe App</title>
  </head>
  <body>
    <div class="main-image">
      <img src="{% static 'recipes/images/recipe-home.jpg' %}" alt="home" />
    </div>
    <nav class="navbar">
      <div class="title">
        <h1>Recipe App</h1>
      </div>

      <div class="profile">
        <a href="/create/">Create Recipe</a>
        <a href="/about/">About Me</a>
        <a href="{%url 'logout' %}"> Logout </a>
      </div>
    </nav>
    <div class="recipe-modal">
      <span
        ><a class="main-header" href="{%url 'recipes:list' %}"
          >Back to all recipes</a
        ></span
      >
      <h2>{{object.name}}</h2>

      <div class="details-main">
        <div class="details-extra">
          <img src="{{object.pic.url}}" width="200" />
        </div>
        <div class="ing-dir">
          <b>Cooking Time (min): </b> {{object.cooking_time}} <br /><br />
          <b>Difficulty: </b> {{object.calculate_difficulty}} <br />
          <br />
          <b>Ingredients: </b> {{object.ingredients}} <br /><br />
          <b>Directions: </b> {{object.directions}} <br />
        </div>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
      rel="stylesheet"
    />
    <script src="{% static 'recipes/home.js' %}" defer></script>
    <title>Recipe App Home</title>
  </head>
  <body>
    <div class="main-image">
      <img src="{% static 'recipes/images/recipe-home.jpg' %}" alt="home" />
    </div>

    <div class="header">
      <h2>Welcome to the Recipe App!</h2>
    </div>
    <div class="subheader">
      <h3>Sign in to explore our collection of recipes.</h3>
    </div>
    <div style="text-align: center">
      <button class="login-button">
        <a href="{%url 'login' %}" style="color: white">Login</a>
      </button>
    </div>
  </body>
</html>